config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"

  # ----- 汎用ページのルーティング設定
  get "help", to: "static_pages#help"
  get "about", to: "static_pages#about"
  get "contact", to: "static_pages#contact"
  get "signup", to: "users#new"
  post "signup", to: "users#create"

  # ----- ユーザ関連のルーティング設定
  resources :users

  # ----- ログイン機能のルーティング設定
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :account_activations, only: [:edit]

  # ----- マイクロポスト関連のルーティング設定
  resources :microposts, only: [:create, :destroy]

  # ----- フォロー機能に関するルーティング設定
  # フォローしているユーザ一覧、フォロワー一覧画面のルーティング設定
  resources :users do
    member do
      get(:following, :followers)
    end
  end
  get "following", to: "users#following"

  # フォロー・フォロー解除機能のルーティング設定
  resources :follower_followeds, only: [:create, :destroy]
end

app/views/shared/_error_messages.html.erb
<% if flash[:error]&.any? %>
<div id="error_explanation">
  <div class=" alert alert-danger">
    The form contains <%= pluralize(flash[:error].count, "error") %>
  </div>
  <ul>
    <% flash[:error].each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items&.any? %>

<%# ページネーションバー %>
<%= will_paginate(@feed_items) %>

<ol class="microposts">
    <%= render @feed_items %>
</ol>

<%# ページネーションバー %>
<%= will_paginate(@feed_items) %>

<% end %>

app/views/shared/_home_info.html.erb
<div class="center jumbotron">
    <h1>Welcom to the Sample App</h1>

    <h2>
        This is the home page for the
        <a href="https://railstutorial.jp/">Ruby on Rails Tutorial</a>
        sample application.
    </h2>

    <%= link_to  "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

app/views/shared/_micropost_form.html.erb
<%= form_with(model: @micropost, local: true) do |f| %>
<%= render "shared/error_messages", {object: f.object} %>
<div class="field">
    <%= f.text_area(:content, placeholder:"Compose new micropost...") %>
</div>
<span class="picture">
    <%= f.file_field(:picture, {accept: "image/jpeg, image/gif, image/png"}) %>
</span>
<%= f.submit("Post", class:"btn btn-primary") %>
<% end %>

<script type="text/javascript">
    $('#micropost_picture').bind(
        "change",
        function() {
            var size_in_megabytes = this.files[0].size
            if (size_in_megabytes > parseInt('<%= 5. megabyte %>', 10)) {
                alert('<%= t("errors.messages.max_size_error", max_size: "5MB") %>')
            }
        }
    );
</script>

app/views/shared/_stats.html.erb
<%# ユーザがnilの場合は、現在ユーザを取得し直す %>
<% @user ||= current_user %>

<div class="stats">
    <a href="<%= following_user_path(@user) %>">
        <strong id="following" class="stat">
            <%= @user.following.count %>
        </strong>
        following
    </a>
    <a href="<%= followers_user_path(@user) %>">
        <strong id="followers" class="stat">
            <%= @user.followers.count %>
        </strong>
        followers
    </a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size:50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.microposts.count, "micropost") %></span>