config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"

  # ----- 汎用ページのルーティング設定
  get "help", to: "static_pages#help"
  get "about", to: "static_pages#about"
  get "contact", to: "static_pages#contact"
  get "signup", to: "users#new"
  post "signup", to: "users#create"

  # ----- ユーザ関連のルーティング設定
  resources :users

  # ----- ログイン機能のルーティング設定
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :account_activations, only: [:edit]

  # ----- マイクロポスト関連のルーティング設定
  resources :microposts, only: [:create, :destroy]

  # ----- フォロー機能に関するルーティング設定
  # フォローしているユーザ一覧、フォロワー一覧画面のルーティング設定
  resources :users do
    member do
      get(:following, :followers)
    end
  end
  get "following", to: "users#following"

  # フォロー・フォロー解除機能のルーティング設定
  resources :follower_followeds, only: [:create, :destroy]
end

app/views/layouts/_footer.html.erb
<footer class>
  <small>
    The <a href="https://railstutorial.jp">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com">Michael Hartl</a>
  </small>
  <br>
  <small>
    <a target="_blank" href="https://icons8.jp/icons/set/bird">鳥 icon</a>
    アイコン <a target="_blank" href="https://icons8.jp">アイコン8</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", root_path, id:"logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <% if logged_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Account<b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Users", users_path %></li>
            <li><%= link_to "Profile", user_path(current_user) %></li>
            <li><%= link_to "Settings", edit_user_path(current_user) %></li>
            <li class="divider"></li>
            <li><%= link_to "Log out", logout_path, {method: :delete} %></li>
          </ul>
        </li>
        <% else %>
        <li>
          <%= link_to "Log in", login_path %>
        </li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <%= favicon_link_tag('favicon.ico') %>
  <title><%= full_title(yield(:title)) %></title>
  <%= render  "layouts/rails_default" %>
  <%= render  "layouts/shim" %>
</head>

<body>
  <%= render  "layouts/header" %>
  <div class="container">
    <div class="row">
      <%
        # 以下の理由により、明示したflashのみ表示する。
        # ・flash[:error]はValidationなどのエラー表示のため、別のパーシャルで使用するため(2重表示を防ぐ)
        # ・BootstrapのCSSに対応している文字列(alert-successなど)のみ許容するため
        #   参考：https://getbootstrap.com/docs/4.0/components/alerts/
      %>
      <% if(
        flash[:primary] || flash[:secondary] || flash[:success]||
        flash[:danger] || flash[:warning] ||
        flash[:info] || flash[:light] || flash[:dark]
      )%>
      <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <% end %>
    </div>
    <%= yield %>
    <%= render  "layouts/footer" %>
    <%= debug(params) if Rails.env.development? %>
  </div>
</body>


</html>